name: Docker Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  workflow_dispatch:  # Allows manual trigger of the workflow from the Actions tab

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from GitHub repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app .

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app

    # SSH into EC2 and deploy Docker container
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}  # The public IP of your EC2 instance
        username: ${{ secrets.EC2_USERNAME }}  # Change to your EC2 username (usually ec2-user or ubuntu)
        key: ${{ secrets.EC2_PRIVATE_KEY }}  # The private key of your EC2 instance (stored in GitHub Secrets)
        script: |
          # Update packages and install Docker if needed
          sudo yum update -y
          sudo amazon-linux-extras install docker -y
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          newgrp docker

          # Pull the latest Docker image from Docker Hub
          docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app

          # Run the Docker container
          docker run -d -p 80:3000 \
            -e MONGODB_URI=${{ secrets.MONGO_URI }} \
            -e MONGODB_PORT=${{ secrets.PORT }} \
            ${{ secrets.DOCKER_USERNAME }}/nodejs-cicd-app
